# publishDir = "docs"

# baseURL = "https://qcrypt-website.netlify.app/"
languageCode = "en"
title = "QCrypt Conference Website"

# Theme
theme = "devfest-theme-hugo"

# Params
enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

GoogleAnalytics = "G-221GMGECQ6"

[params]
    title = "QCrypt Conference Website"
    date = "2024-09-02"
    year = 2024
    description = "International Conference on Quantum Cryptography"
    images = ["/images/social-share.jpg"]
    email = "webmaster@qcrypt.net"
    keywords = "event, quantum cryptography, QCrypt"
    copyright = "We :heart: sheep"
    copyright_link = "https://github.com/QCrypt/qcrypt-website"
    # cfpUrl = ""
    # subscriptionUrl = ""
    appleTouchIcon = "/apple-touch-icon.png"
    favicon32 = "/favicon-32x32.png"
    favicon16 = "/favicon-16x16.png"
    manifest = "/manifest.json"
    safariPinnedTab = "/safari-pinned-tab.svg"
    themeColor = "#086788"

[params.logos]
    [params.logos.2024]
        jumbo = "/images/logos/QCrypt_2024_logo_final.png"
        header = "/images/logos/QC_24_2.png"
    [params.logos.2023]
        jumbo = "/images/logos/QuCrC23_Logo.png"
        header = "/images/logos/QuCrC23_Logo.png"
    footer = "/images/logos/netlify-color-accent.svg"
    footer_link = "https://www.netlify.com"

[server]
[[server.redirects]]
    from = "/"
    to = "/2024/"
    status = 302
    force = true 

[menu]
  [[menu.2024]]
    name = "Home"
    weight = 10
    identifier = "home"
    pageRef = '/2024'
  [[menu.2024]]
    name = "Technical Program"
    weight = 20
    identifier = "technical-program"
  [[menu.2024]]
    name = "Call"
    weight = 10
    pageRef = "/2024/call"
    identifier = "call"
    parent = "technical-program"
  [[menu.2024]]
    name = "Schedule"
    weight = 20
    pageRef = "/2024/schedule"
    identifier = "schedule"
    parent = "technical-program"
  [[menu.2024]]
    name = "Attend"
    weight = 30
    identifier = "attend"
  [[menu.2024]]
    name = "Venue"
    weight = 10
    pageRef = "/2024/venue"
    identifier = "venue"
    parent = "attend"
  [[menu.2024]]
    name = "Pictures"
    weight = 20
    pageRef = "/2024/pictures"
    identifier = "pictures"
    parent = "attend"
  [[menu.2024]]
    name = "Sponsor"
    weight = 40
    identifier = "sponsor"
    pageReg = "/2024/partners"
  [[menu.2024]]
    name = "Committees"
    weight = 50
    identifier = "committees"
    pageReg = "/2024/team"



[languages]
[languages.en]
    weight = 1
    languageName = "us"

[taxonomies]
    tag = "tags"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        anonymizeIP = false
        disable = false
        respectDoNotTrack = false
        useSessionStorage = false
    [privacy.instagram]
        disable = true
        simple = false
    [privacy.twitter]
        disable = false
        enableDNT = false
        simple = false
    [privacy.vimeo]
        disable = true
        simple = false
    [privacy.youtube]
        disable = true
        privacyEnhanced = true
