# publishDir = "docs"

baseURL = "https://qip-website.netlify.app/"
languageCode = "en"
title = "QIP Conference Website"

# Theme
theme = "devfest-theme-hugo"

# Params
enableEmoji = true
enableRobotsTXT = true
enableMissingTranslationPlaceholders = true

# Google Analytics are currently disabled, 
# using it would officially require a cookie banner at least in the EU, and we don't have one...
# it's probably better not to track people anyways.
# GoogleAnalytics = "G-221GMGECQ6"

[services]
  [services.googleAnalytics]
    id = "G-221GMGECQ6"

[params]
    title = "QIP Conference Website"
    date = "2027-01-10"
    currentYear = 2027
    description = "International Conference on Quantum Information Processing (QIP)"
    images = ["/images/social-share.jpg"]
    email = "webmaster@qipconference.org"
    keywords = "event, quantum computation, communication, cryptography, QIP"
    copyright = "We :heart: quantum"
    copyright_link = "https://github.com/IAQI/qip-website"
    # cfpUrl = "/2024/call"
    # subscriptionUrl = ""
    appleTouchIcon = "/apple-touch-icon.png"
    favicon32 = "/favicon-32x32.png"
    favicon16 = "/favicon-16x16.png"
    manifest = "/site.webmanifest"
    # safariPinnedTab = "/safari-pinned-tab.svg"

[params.2024]
  city = "Taipei, Taiwan"
  timeanddate_cityid = 241
  themeColor = "#d71d1f"
  [params.2024.logos]
    jumbo = "/images/2024/qip2024-biglogo.png"
    header = "/images/2024/qip2024-logo.png"
    banner = "/images/2024/banner-2024.png"

[params.2027]
  city = "Singapore"
  timeanddate_cityid = 236
  themeColor = "#d71d1f"
  [params.2027.logos]
    jumbo = "/images/2027/background-2027.png"
    header = "/images/2027/qip-logo-2027.png"
    banner = "/images/2027/banner-2027.jpg"

[params.logos]
    footer = "/images/logos/netlify-color-accent.svg"
    footer_link = "https://www.netlify.com"

[server]
  [[server.redirects]]
      from = "/"
      to = "/2027/"
      status = 302
      force = true 

  [[menu.2024]]
    name = "Home"
    weight = 10
    identifier = "home"
    pageRef = '/2024'
  [[menu.2024]]
    name = "Technical Program"
    weight = 20
    identifier = "technical-program"
  [[menu.2024]]
    name = "Attend"
    weight = 30
    identifier = "attend"
  [[menu.2024]]
    name = "Sponsors"
    weight = 40
    identifier = "sponsors"
    pageRef = "/2024/partners"
  [[menu.2024]]
    name = "Committees"
    weight = 50
    identifier = "committees"
    pageRef = "/2024/team"

  [[menu.2027]]
    name = "Home"
    weight = 10
    identifier = "home"
    pageRef = '/2027'
  [[menu.2027]]
    name = "Technical Program"
    weight = 20
    identifier = "technical-program"
  [[menu.2027]]
    name = "Attend"
    weight = 30
    identifier = "attend"
  [[menu.2027]]
    name = "Sponsors"
    weight = 40
    identifier = "sponsors"
    pageRef = "/2027/partners"
  [[menu.2027]]
    name = "Committees"
    weight = 50
    identifier = "committees"
    pageRef = "/2027/team"




[languages]
[languages.en]
    weight = 1
    languageName = "us"

[taxonomies]
    tag = "tags"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[privacy]
    [privacy.disqus]
        disable = true
    [privacy.googleAnalytics]
        anonymizeIP = false
        disable = false
        respectDoNotTrack = false
        useSessionStorage = false
    [privacy.instagram]
        disable = true
        simple = false
    [privacy.twitter]
        disable = false
        enableDNT = false
        simple = false
    [privacy.vimeo]
        disable = true
        simple = false
    [privacy.youtube]
        disable = true
        privacyEnhanced = true
