#!/usr/bin/env python3
### This script (generated by GPT4, modified for CLI) sanitizes the JSON export from HotCRP to remove sensitive data

import json
import argparse
import sys
import re
import time
import urllib.parse
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

# The keys you want to remove
keys_to_remove = {"email", "pc_conflicts", "metadata", "eligible_student_paper_prize", "talk_poster", "submitted_at", "status", "submitted", "submission", "technical_manuscript", "poster_consideration", "submission_eligible_student_paper_prize", "modified_at", "contact"}

def search_arxiv(title, authors=None):
    """Search arXiv for a paper by title and optionally authors.
    
    Args:
        title: Paper title to search for
        authors: List of author dictionaries (optional)
        
    Returns:
        arXiv ID if found, None otherwise
    """
    if not title:
        return None
    
    # Build search query
    query_parts = [f'ti:"{title}"']
    
    # Add first author if available
    if authors and len(authors) > 0:
        first_author = authors[0]
        author_name = f"{first_author.get('first', '')} {first_author.get('last', '')}".strip()
        if author_name:
            query_parts.append(f'au:"{author_name}"')
    
    search_query = ' AND '.join(query_parts)
    
    # Build arXiv API URL
    base_url = 'http://export.arxiv.org/api/query?'
    params = {
        'search_query': search_query,
        'max_results': '1',
        'sortBy': 'relevance',
        'sortOrder': 'descending'
    }
    url = base_url + urllib.parse.urlencode(params)
    
    try:
        # Rate limiting - arXiv requests max 1 request per 3 seconds
        time.sleep(3)
        
        with urllib.request.urlopen(url, timeout=10) as response:
            xml_data = response.read()
        
        # Parse XML response
        root = ET.fromstring(xml_data)
        
        # arXiv API uses Atom namespace
        ns = {'atom': 'http://www.w3.org/2005/Atom'}
        
        # Find the first entry
        entry = root.find('atom:entry', ns)
        if entry is not None:
            # Get the arXiv ID from the entry ID
            entry_id = entry.find('atom:id', ns)
            if entry_id is not None:
                # Extract ID from URL like http://arxiv.org/abs/2503.19125v1
                arxiv_url = entry_id.text
                match = re.search(r'arxiv\.org/abs/(\d{4}\.\d{4,5})(v\d+)?', arxiv_url)
                if match:
                    return match.group(1)  # Return ID without version
        
    except Exception as e:
        print(f"Warning: arXiv search failed for '{title[:50]}...': {e}", file=sys.stderr)
    
    return None

def normalize_arxiv_id(arxiv_value):
    """Extract and normalize arXiv ID(s) from various formats.
    
    Args:
        arxiv_value: String containing arXiv information in various formats
        
    Returns:
        Normalized arXiv ID(s) as a string, list, or original value if no ID found
    """
    if not isinstance(arxiv_value, str):
        return arxiv_value
    
    # Pattern to match arXiv IDs (e.g., 2503.19125, 2310.05213v3)
    # Matches YYMM.NNNNN or YYMM.NNNNNvX format
    arxiv_pattern = r'\b(\d{4}\.\d{4,5}(?:v\d+)?)\b'
    
    # Find all arXiv IDs in the string
    matches = re.findall(arxiv_pattern, arxiv_value)
    
    if matches:
        # Remove version numbers (vX) from arXiv IDs
        clean_ids = [re.sub(r'v\d+$', '', match) for match in matches]
        # Remove duplicates while preserving order
        seen = set()
        unique_ids = []
        for id in clean_ids:
            if id not in seen:
                seen.add(id)
                unique_ids.append(id)
        # Return list if multiple IDs, single string if one ID
        return unique_ids if len(unique_ids) > 1 else unique_ids[0]
    
    # If no arXiv ID found, return original value
    return arxiv_value

def categorize_decision(decision):
    """Categorize decision into talk type.
    
    Args:
        decision: The decision string from HotCRP
        
    Returns:
        A category string: 'long-plenary', 'plenary', or 'talk'
    """
    if not isinstance(decision, str):
        return 'talk'
    
    decision_lower = decision.lower()
    
    if 'longplenary' in decision_lower:
        return 'long-plenary'
    elif 'plenary' in decision_lower:
        return 'plenary'
    else:
        return 'talk'

def extract_merge_pids(tags, current_pid):
    """Extract PIDs from merge tags, excluding the current PID.
    
    Args:
        tags: List of tag objects
        current_pid: The PID of the current paper
        
    Returns:
        List of PIDs this paper is merged with (excluding itself)
    """
    if not isinstance(tags, list):
        return []
    
    for tag in tags:
        if isinstance(tag, dict):
            tag_value = tag.get("tag", "")
            if tag_value.startswith("merge-"):
                # Extract PIDs from tag like "merge-108-377" or "merge-206-267-387"
                pid_parts = tag_value.replace("merge-", "").split("-")
                try:
                    pids = [int(p) for p in pid_parts]
                    # Return all PIDs except the current one
                    merged_pids = [p for p in pids if p != current_pid]
                    return merged_pids
                except ValueError:
                    # Skip if PIDs can't be parsed as integers
                    continue
    return []

def sanitize_data(data, current_pid=None):
    """Recursively sanitize a dictionary by removing specific keys and filtering tags.
    
    Args:
        data: The data to sanitize
        current_pid: The PID of the current paper (for extracting merge info)
    """
    if isinstance(data, dict):
        sanitized = {}
        has_arxiv_id = False
        
        # Extract current PID if this is a paper object
        if "pid" in data and current_pid is None:
            current_pid = data.get("pid")
        
        for key, value in data.items():
            if key in keys_to_remove:
                continue
            # Convert arxiv_number_url to options["arxiv-id"] format
            if key == "arxiv_number_url" and isinstance(value, str):
                arxiv_id = normalize_arxiv_id(value)
                # Only add if we found a valid arXiv ID
                if arxiv_id != value or (isinstance(arxiv_id, str) and '.' in arxiv_id):
                    if "options" not in sanitized:
                        sanitized["options"] = {}
                    sanitized["options"]["arxiv-id"] = arxiv_id
                    has_arxiv_id = True
                continue  # Don't keep the original arxiv_number_url field
            # Categorize decision type and add to options
            elif key == "decision" and isinstance(value, str):
                sanitized[key] = sanitize_data(value, current_pid)
                category = categorize_decision(value)
                if "options" not in sanitized:
                    sanitized["options"] = {}
                sanitized["options"]["talk-type"] = category
            # Filter tags to only keep those with "merge" in the tag value
            elif key == "tags" and isinstance(value, list):
                merge_tags = [
                    sanitize_data(tag, current_pid) for tag in value 
                    if isinstance(tag, dict) and "merge" in tag.get("tag", "")
                ]
                sanitized[key] = merge_tags
                
                # Add mergedwith field if there are merge tags
                if merge_tags and current_pid is not None:
                    merged_pids = extract_merge_pids(value, current_pid)
                    if merged_pids:
                        # For compatibility with 2024 format, use single value if only one merger
                        # Use array for multi-way mergers (3+)
                        sanitized["mergedwith"] = merged_pids[0] if len(merged_pids) == 1 else merged_pids
            else:
                sanitized[key] = sanitize_data(value, current_pid)
        
        # If this is a paper object without an arXiv ID, try searching arXiv
        if "pid" in sanitized and not has_arxiv_id and "title" in sanitized:
            print(f"Searching arXiv for paper #{sanitized['pid']}: {sanitized['title'][:60]}...")
            arxiv_id = search_arxiv(sanitized['title'], sanitized.get('authors'))
            if arxiv_id:
                print(f"  Found: {arxiv_id}")
                if "options" not in sanitized:
                    sanitized["options"] = {}
                sanitized["options"]["arxiv-id"] = arxiv_id
            else:
                print(f"  Not found on arXiv")
        
        return sanitized
    elif isinstance(data, list):
        return [sanitize_data(value, None) for value in data]
    else:
        return data

def load_json_file(file_path):
    """Load and return JSON data from a file."""
    try:
        with open(file_path, 'r') as f:
            return json.load(f)
    except FileNotFoundError:
        print(f"Error: File '{file_path}' not found.", file=sys.stderr)
        sys.exit(1)
    except json.JSONDecodeError as e:
        print(f"Error: Invalid JSON in file '{file_path}': {e}", file=sys.stderr)
        sys.exit(1)

def sanitize_json_files(input_files, output_file):
    """Read multiple JSON files, sanitize them, and write the combined sanitized data to a new JSON file."""
    combined_data = []
    
    for input_file in input_files:
        print(f"Processing: {input_file}")
        data = load_json_file(input_file)
        
        # Handle both single objects and arrays
        if isinstance(data, list):
            combined_data.extend(data)
        else:
            combined_data.append(data)
    
    # Sanitize the combined data
    sanitized_data = sanitize_data(combined_data)
    
    # Write to output file
    try:
        with open(output_file, 'w') as f:
            json.dump(sanitized_data, f, indent=4)
        print(f"Successfully wrote sanitized data to: {output_file}")
    except IOError as e:
        print(f"Error: Could not write to file '{output_file}': {e}", file=sys.stderr)
        sys.exit(1)

def main():
    parser = argparse.ArgumentParser(
        description='Sanitize HotCRP JSON exports by removing sensitive data. Supports multiple input files.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='''
Examples:
  %(prog)s input.json -o output.json
  %(prog)s file1.json file2.json file3.json -o combined.json
  %(prog)s *.json -o all_sanitized.json
        '''
    )
    
    parser.add_argument('input_files', nargs='+', metavar='INPUT_FILE',
                        help='One or more JSON files to sanitize')
    parser.add_argument('-o', '--output', required=True, metavar='OUTPUT_FILE',
                        help='Output file path for sanitized JSON')
    
    args = parser.parse_args()
    
    # Validate input files exist
    for input_file in args.input_files:
        if not Path(input_file).exists():
            print(f"Error: Input file '{input_file}' does not exist.", file=sys.stderr)
            sys.exit(1)
    
    sanitize_json_files(args.input_files, args.output)

if __name__ == '__main__':
    main()
